# Generated by Django 4.2.10 on 2026-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionperfil', models.TextField(blank=True, null=True, verbose_name='Descripción del perfil')),
                ('perfilactivo', models.IntegerField(default=0, verbose_name='Perfil activo')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('lugarnacimiento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de nacimiento')),
                ('fechanacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('numerocedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de cédula')),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo')),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado civil')),
                ('licenciaconducir', models.CharField(blank=True, max_length=50, null=True, verbose_name='Licencia de conducir')),
                ('telefonoconvencional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono convencional')),
                ('telefonofijo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono fijo')),
                ('direcciontrabajo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección de trabajo')),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección domiciliaria')),
                ('sitioweb', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=200, verbose_name='Nombre producto')),
                ('estadoproducto', models.CharField(default='Disponible', max_length=50, verbose_name='Estado producto')),
                ('valordelbien', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del bien')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para front')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionreconocimiento', models.CharField(max_length=200, verbose_name='Descripción reconocimiento')),
                ('tiporeconocimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo reconocimiento')),
                ('fechareconocimiento', models.DateField(verbose_name='Fecha reconocimiento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para front')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=200, verbose_name='Nombre producto')),
                ('fechaproducto', models.DateField(blank=True, null=True, verbose_name='Fecha producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para front')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=200, verbose_name='Nombre recurso')),
                ('clasificador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clasificador')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para front')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=200, verbose_name='Cargo desempeñado')),
                ('nombrempresa', models.CharField(max_length=200, verbose_name='Nombre empresa')),
                ('fechainiciogestion', models.DateField(verbose_name='Fecha inicio gestión')),
                ('fechafingestion', models.DateField(verbose_name='Fecha fin gestión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para front')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado')),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=200, verbose_name='Nombre curso')),
                ('entidadpatrocinadora', models.CharField(max_length=200, verbose_name='Entidad patrocinadora')),
                ('fechafin', models.DateField(verbose_name='Fecha fin')),
                ('totalhoras', models.IntegerField(default=0, verbose_name='Total horas')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para front')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado')),
            ],
        ),
    ]
