# Generated by Django 4.2.10 on 2026-02-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospersonales',
            options={},
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='descripcioncurso',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='emailempresapatrocinadora',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='fechainicio',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='telefonocontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='emailempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='lugarempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='entidadpatrocinadora',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='telefonocontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='idperfilconqueestaactivo',
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción adicional'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Activar para front'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='entidadpatrocinadora',
            field=models.CharField(max_length=200, verbose_name='Entidad patrocinadora'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fechafin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='nombrecurso',
            field=models.CharField(max_length=200, verbose_name='Nombre curso'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='totalhoras',
            field=models.IntegerField(default=0, verbose_name='Total horas'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del perfil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección domiciliaria'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección de trabajo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Licencia de conducir'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(default=0, verbose_name='Perfil activo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono convencional'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Activar para front'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=200, verbose_name='Cargo desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(verbose_name='Fecha fin gestión'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(verbose_name='Fecha inicio gestión'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=200, verbose_name='Nombre empresa'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Activar para front'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='clasificador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clasificador'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='nombrerecurso',
            field=models.CharField(max_length=200, verbose_name='Nombre recurso'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Activar para front'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fechaproducto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha producto'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='nombreproducto',
            field=models.CharField(max_length=200, verbose_name='Nombre producto'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Activar para front'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=200, verbose_name='Descripción reconocimiento'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fechareconocimiento',
            field=models.DateField(verbose_name='Fecha reconocimiento'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales', verbose_name='Perfil asociado'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='tiporeconocimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo reconocimiento'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Activar para front'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(default='Disponible', max_length=50, verbose_name='Estado producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=200, verbose_name='Nombre producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del bien'),
        ),
    ]
