# Generated by Django 4.2.10 on 2026-02-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='fechainiciogestion',
            new_name='fechainicogestion',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='telefonocontactoempresarial',
            new_name='telefoncontactoempresarial',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='logo_curso',
            field=models.ImageField(blank=True, null=True, upload_to='logos_cursos/'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='idiomas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='archivorecurso',
            field=models.FileField(blank=True, null=True, upload_to='archivos_academicos/'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='imagen_recurso',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_academicas/'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='urlrecurso',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='archivoproducto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_laborales/'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_laborales/'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='urlproducto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='imagen_reconocimiento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_reconocimientos/'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='emailempresapatrocinadora',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='nombrecurso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='nombrerecurso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='nombreproducto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
