# Generated by Django 4.2.10 on 2026-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_fechainiciogestion_experiencialaboral_fechainicogestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='fechainicogestion',
            new_name='fechainiciogestion',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='telefoncontactoempresarial',
            new_name='telefonocontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='logo_curso',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='github',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='idiomas',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='logo_empresa',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='archivorecurso',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='imagen_recurso',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='urlrecurso',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='archivoproducto',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='imagen_producto',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='urlproducto',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='imagen_reconocimiento',
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='emailempresapatrocinadora',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='nombrecurso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='nombrerecurso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='nombreproducto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=100),
        ),
    ]
