# Generated by Django 4.2.10 on 2026-02-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_fechainicogestion_experiencialaboral_fechainiciogestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='email',
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
