# Generated by Django 4.2.10 on 2026-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_datospersonales_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursorealizado',
            old_name='activarparaqueseveaenfront',
            new_name='activarparaqueeseveaenfront',
        ),
        migrations.RenameField(
            model_name='cursorealizado',
            old_name='idperfilconqueestaactivo',
            new_name='idperfilconqueestaativo',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='activarparaqueseveaenfront',
            new_name='activarparaqueeseveaenfront',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='fechainiciogestion',
            new_name='fechainicogestion',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='idperfilconqueestaactivo',
            new_name='idperfilconqueestaativo',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='telefonocontactoempresarial',
            new_name='telefoncontactoempresarial',
        ),
        migrations.RenameField(
            model_name='productoacademico',
            old_name='activarparaqueseveaenfront',
            new_name='activarparaqueeseveaenfront',
        ),
        migrations.RenameField(
            model_name='productolaboral',
            old_name='activarparaqueseveaenfront',
            new_name='activarparaqueeseveaenfront',
        ),
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='activarparaqueseveaenfront',
            new_name='activarparaqueeseveaenfront',
        ),
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='idperfilconqueestaactivo',
            new_name='idperfilconqueestaativo',
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='activarparaqueseveaenfront',
            new_name='activparaqueuseveaefront',
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='idperfilconqueestaactivo',
            new_name='idperfilconqueestaatcivo',
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='nombreproducto',
            new_name='nombrepreducto',
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateTimeField(),
        ),
    ]
